// <auto-generated />
using BloodswordGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodswordGame.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250731110604_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodswordGame.Data.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("CurrentParagraphId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentParagraphId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("BloodswordGame.Data.Models.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromParagraphId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToParagraphId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromParagraphId");

                    b.HasIndex("ToParagraphId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("BloodswordGame.Data.Models.Paragraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paragraphs");
                });

            modelBuilder.Entity("BloodswordGame.Data.Models.Character", b =>
                {
                    b.HasOne("BloodswordGame.Data.Models.Paragraph", "CurrentParagraph")
                        .WithMany()
                        .HasForeignKey("CurrentParagraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentParagraph");
                });

            modelBuilder.Entity("BloodswordGame.Data.Models.Choice", b =>
                {
                    b.HasOne("BloodswordGame.Data.Models.Paragraph", "FromParagraph")
                        .WithMany("Choices")
                        .HasForeignKey("FromParagraphId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodswordGame.Data.Models.Paragraph", "ToParagraph")
                        .WithMany()
                        .HasForeignKey("ToParagraphId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromParagraph");

                    b.Navigation("ToParagraph");
                });

            modelBuilder.Entity("BloodswordGame.Data.Models.Paragraph", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
